spring:
    h2:
        console.enabled=true
    datasource:
        url: jdbc:h2:mem:mydb
        driverClassName: org.h2.Driver
        username: db
        password:
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
